### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by Sekai1942** [mardini1974/ATCduino#2]
Hi.
I get the error when i start linuxcnc:
ATCduino_gui.hal:1: Pin 'ATCduinoui.hal_spinbutton1-s' does not exist

Have any idea why?
Thanks

**Comment by Sekai1942** [comment]
New problem.
I reinstall everything.Now it shows only:
`Found ATC (Auto tool changer) and connecting on port /tty/USB0.................................................................................................
...................................................................................................................................
................................................................................................................................. `

and i waited 15 min and it goes on forever.
Any idea?

**Comment by mardini1974** [comment]
Hello sorry for the late reply, i think the baud rate is not correct with the arduino try to communicate with deferent settings

**Comment by Sekai1942** [comment]
That is weird because i used the arduino serial terminal and it comunicate just fine.
The arduino is closed when i startup the linuxcnc.
Maybe something with the Python serial plugin?

**Comment by Sekai1942** [comment]
I install linux mint 20 and manualy add linuxcnc uspace.
it starts but it shuts down 
`LINUXCNC - 2.8.2-64-g8440b9692
Machine configuration directory is '/home/cnc/linuxcnc/configs/freza'
Machine configuration file is 'freza.ini'
Starting LinuxCNC...
Found file(REL): ./freza.hal
Note: Using POSIX non-realtime
config string '0 out'
Found file(REL): ./custom.hal
Found file(REL): ./ATCduino.hal
Waiting for component 'ATCduino' to become ready.Found ATC (Auto tool changer) and connecting on port '/dev/ttyUSB0'

USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
Waiting for component 'inihal' to become ready...(0, ' = ', '/usr/bin/gmoccapy')
(1, ' = ', '-ini')
(2, ' = ', '/home/cnc/linuxcnc/configs/freza/freza.ini')
Entry = trivkins
Entry = coordinates=XYZ
found the following coordinates xyz

**** GMOCCAPY GETINIINFO **** 
Number of joints = 3
3 COORDINATES found = xyz
joint 0 = axis x
joint 1 = axis y
joint 2 = axis z
{0: 'x', 1: 'y', 2: 'z'}

**** GMOCCAPY GETINIINFO **** 

[KINS] KINESTYPE is trivkins
**** GMOCCAPY GETINIINFO **** 
No MIN_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 0.1 degree / min
**** GMOCCAPY GETINIINFO **** 
No DEFAULT_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 360 degree / min
**** GMOCCAPY GETINIINFO **** 
No MAX_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 3600 degree / min
**** GMOCCAPY GETINIINFO **** 
No MAX_RAPID_OVERRIDE entry found in [DISPLAY] of INI file 
 Default settings 100 % applied!
**** GMOCCAPY GETINIINFO **** 
Preference file path: /home/cnc/linuxcnc/configs/freza/freza.pref
**** GMOCCAPY GETINIINFO **** 
 No DEFAULT_SPINDLE_SPEED entry found in [DISPLAY] of INI file
**** GMOCCAPY INFO ****
**** no valid probe config in INI File ****
**** disabled tool measurement ****
**** GMOCCAPY INFO ****
**** Entering make_DRO
axis_list = ['x', 'y', 'z']
**** GMOCCAPY INFO ****
**** Entering make ref axis button
('Filepath = ', '/usr/share/gmoccapy/images/ref_all.png')
('Filepath = ', '/usr/share/gmoccapy/images/ref_x.png')
('Filepath = ', '/usr/share/gmoccapy/images/ref_y.png')
('Filepath = ', '/usr/share/gmoccapy/images/ref_z.png')
('Filepath = ', '/usr/share/gmoccapy/images/unhome.png')
**** GMOCCAPY INFO ****
**** Entering make touch button
**** GMOCCAPY INFO ****
**** Entering make jog increments
**** GMOCCAPY INFO ****
**** Entering make jog button
**** GMOCCAPY INFO ****
**** Entering make macro button
found 0 Macros
**** GMOCCAPY INFO ****
**** arrange DRO
3
**** GMOCCAPY INFO ****
**** Place in table
**** GMOCCAPY INFO ****
**** get DRO order
**** GMOCCAPY INFO ****
**** arrange JOG button
less than 6 axis
....../usr/bin/gmoccapy:311: GtkWarning: Invalid icon size 48

  self.widgets.window1.show()
..USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
....................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
....................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
...................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
....................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
....................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
.....**** GMOCCAPY INFO ****
**** no audio available! ****
**** PYGST libray not installed? ****
**** is python-gstX.XX installed? ****
**** GMOCCAPY INFO ****
**** Entering init gremlin ****
..Kinematics type changed
......module 'ATCduinoui' skipped - import error: No module named cfgparse
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'Save'
  builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_Piston_off_clicked'
  builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_hal_ATC_piston_clicked'
  builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_Homing_clicked'
  builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_SaveEEprom_clicked'
  builder.connect_signals(handlers)
...77594627
...USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
...................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
....................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
..........emc/task/emctaskmain.cc 3057: can't initialize motion
..........USRMOT: ERROR: command timeout
HAL: ERROR: exit called before init
<commandline>:0: waitpid failed milltask inihal

<commandline>:0: milltask exited without becoming ready
('_set_enable_tooltips = ', True)
**** GMOCCAPY INFO ****
**** virtual keyboard program found : <onboard>
**** GMOCCAPY INFO: Gcode.lang found ****

(gmoccapy:27567): GtkSourceView-CRITICAL **: 09:16:59.682: gtk_source_language_manager_set_search_path: assertion 'lm->priv->ids == NULL' failed
**** GMOCCAPY GETINIINFO **** 
Wrong entry [DISPLAY] CYCLE_TIME in INI File!
Will use gmoccapy default 150
**** GMOCCAPY INFO : inifile = /home/cnc/linuxcnc/configs/freza/freza.ini ****:
**** GMOCCAPY INFO : postgui halfile = postgui_list.hal ****:
Waiting for component 'abs' to become ready..Waited 3 seconds for master.  giving up.
Note: Using POSIX non-realtime
.
ATCduino_gui.hal:13: Pin 'ATCduinoui.hal_spinbutton13-s' does not exist
Shutting down and cleaning up LinuxCNC...
ATC has been disconnected
Note: Using POSIX non-realtime
pwmgen: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
stepgen: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
hal_parport: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
motmod: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
trivkins: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
<commandline>:0: unloadrt failed
Note: Using POSIX non-realtime
LinuxCNC terminated with an error.  You can find more information in the log:
    /home/cnc/linuxcnc_debug.txt
and
    /home/cnc/linuxcnc_print.txt
as well as in the output of the shell command 'dmesg' and in the terminal
`
before this it told me that /dev/ttyUSB0 did not have permisions to access it.
I did a sudo chmod a+rw /dev/ttyUSB0 and it worked.
The problem is that `ATCduino_gui.hal:13: Pin 'ATCduinoui.hal_spinbutton13-s' does not exist` where to find?

**Comment by mardini1974** [comment]
The spinbutton13-s,spinbutton14-s,spinbutton15-s are taken from Gmoccapy.ini  file, Using the file ATCduinoui.py to read them you need cfgparse python library, check the error above 
`import error: No module named cfgparse` .
try to install it to Linuxcnc python version
I stopped working on LinuxCNC 3 years ago, there is a lot changed also in it, so accept my apologies.

**Comment by Sekai1942** [comment]
Cfgparse Ford nota work.
configparser is the replacement.
Nothing change. I le-am no start.
If i nota allow spinbtton to load, the linuxcnc starts up but when i go to the ATC tab and click piston on or off nothing happens.
Do you remember what vs of debian did You user and kernel.
Thanks

**Comment by mardini1974** [comment]
It was Debian 8 but kernel I don't remember

**Comment by mardini1974** [comment]
All errors are coming from the same file: Piston On/Off, Homing ... etc.
```
.....module 'ATCduinoui' skipped - import error: No module named cfgparse
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'Save'
builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_Piston_off_clicked'
builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_hal_ATC_piston_clicked'
builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_Homing_clicked'
builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_SaveEEprom_clicked'
builder.connect_signals(handlers)
```

try to replace lib to configparser in ATCduinoui.py and run LinuxCNC. make sure that you don't have any errors when starting related to ATC

**Comment by Sekai1942** [comment]
Sorry about my previous post.My phones autocorrect is a mess.
I change cfgparse to configparser and the error is gone but the handlers is still present.
Present setup is linux mint19.4 with kernel 4.19.152 amd64
```
cnc@cnc-HP-t510-Thin-Client:~/linuxcnc/configs/freza$ linuxcnc freza.ini
LINUXCNC - 2.8.2-66-g1ed967b87
Machine configuration directory is '/home/cnc/linuxcnc/configs/freza'
Machine configuration file is 'freza.ini'
Starting LinuxCNC...
Found file(REL): ./freza.hal
Note: Using POSIX non-realtime
config string '0 out'
Found file(REL): ./custom.hal
Found file(REL): ./ATCduino.hal
USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
Waiting for component 'inihal' to become ready.....(0, ' = ', '/usr/bin/gmoccapy')
(1, ' = ', '-ini')
(2, ' = ', '/home/cnc/linuxcnc/configs/freza/freza.ini')
Entry = trivkins
Entry = coordinates=XYZ
found the following coordinates xyz

**** GMOCCAPY GETINIINFO **** 
Number of joints = 3
3 COORDINATES found = xyz
joint 0 = axis x
joint 1 = axis y
joint 2 = axis z
{0: 'x', 1: 'y', 2: 'z'}

**** GMOCCAPY GETINIINFO **** 

[KINS] KINESTYPE is trivkins
**** GMOCCAPY GETINIINFO **** 
No MIN_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 0.1 degree / min
**** GMOCCAPY GETINIINFO **** 
No DEFAULT_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 360 degree / min
**** GMOCCAPY GETINIINFO **** 
No MAX_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 3600 degree / min
**** GMOCCAPY GETINIINFO **** 
No MAX_RAPID_OVERRIDE entry found in [DISPLAY] of INI file 
 Default settings 100 % applied!
**** GMOCCAPY GETINIINFO **** 
Preference file path: /home/cnc/linuxcnc/configs/freza/freza.pref
**** GMOCCAPY GETINIINFO **** 
 No DEFAULT_SPINDLE_SPEED entry found in [DISPLAY] of INI file
**** GMOCCAPY INFO ****
**** no valid probe config in INI File ****
**** disabled tool measurement ****
**** GMOCCAPY INFO ****
**** Entering make_DRO
axis_list = ['x', 'y', 'z']
.**** GMOCCAPY INFO ****
**** Entering make ref axis button
('Filepath = ', '/usr/share/gmoccapy/images/ref_all.png')
('Filepath = ', '/usr/share/gmoccapy/images/ref_x.png')
('Filepath = ', '/usr/share/gmoccapy/images/ref_y.png')
('Filepath = ', '/usr/share/gmoccapy/images/ref_z.png')
('Filepath = ', '/usr/share/gmoccapy/images/unhome.png')
**** GMOCCAPY INFO ****
**** Entering make touch button
**** GMOCCAPY INFO ****
**** Entering make jog increments
**** GMOCCAPY INFO ****
**** Entering make jog button
**** GMOCCAPY INFO ****
**** Entering make macro button
found 0 Macros
**** GMOCCAPY INFO ****
**** arrange DRO
3
**** GMOCCAPY INFO ****
**** Place in table
**** GMOCCAPY INFO ****
**** get DRO order
**** GMOCCAPY INFO ****
**** arrange JOG button
less than 6 axis
.......USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
/usr/bin/gmoccapy:311: GtkWarning: Invalid icon size 48

  self.widgets.window1.show()
...................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
....................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
....................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
....................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
....................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
.......**** GMOCCAPY INFO ****
**** no audio available! ****
**** PYGST libray not installed? ****
**** is python-gstX.XX installed? ****
**** GMOCCAPY INFO ****
**** Entering init gremlin ****
............USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
...Kinematics type changed
........gladevcp: trouble looking for handlers in 'ATCduinoui': 'NoneType' object has no attribute 'set_value'
Traceback (most recent call last):
  File "/usr/bin/gladevcp", line 129, in load_handlers
    objlist = h(halcomp,builder,useropts)
  File "./ATCduinoui.py", line 97, in get_handlers
    return [HandlerClass(halcomp, builder, useropts)]
  File "./ATCduinoui.py", line 27, in __init__
    self.spin.set_value(int(inifile.find("HOMING", "HSPEED") or 0))
AttributeError: 'NoneType' object has no attribute 'set_value'
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'Save'
  builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_Piston_off_clicked'
  builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_hal_ATC_piston_clicked'
  builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_Homing_clicked'
  builder.connect_signals(handlers)
/usr/bin/gladevcp:221: RuntimeWarning: missing handler 'on_SaveEEprom_clicked'
  builder.connect_signals(handlers)
.........USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
60817411
...................USRMOT: ERROR: command timeout
emcMotionInit: emcTrajInit failed
..........emc/task/emctaskmain.cc 3057: can't initialize motion
..........USRMOT: ERROR: command timeout
HAL: ERROR: exit called before init
<commandline>:0: waitpid failed milltask inihal

<commandline>:0: milltask exited without becoming ready
('_set_enable_tooltips = ', True)
**** GMOCCAPY INFO ****
**** virtual keyboard program found : <onboard>
**** GMOCCAPY INFO: Gcode.lang found ****

(gmoccapy:2586): GtkSourceView-CRITICAL **: 16:51:12.926: gtk_source_language_manager_set_search_path: assertion 'lm->priv->ids == NULL' failed
**** GMOCCAPY GETINIINFO **** 
Wrong entry [DISPLAY] CYCLE_TIME in INI File!
Will use gmoccapy default 150
**** GMOCCAPY INFO : inifile = /home/cnc/linuxcnc/configs/freza/freza.ini ****:
**** GMOCCAPY INFO : postgui halfile = postgui_list.hal ****:
Waiting for component 'abs' to become ready.........Waited 3 seconds for master.  giving up.
Note: Using POSIX non-realtime
.
ATCduino_gui.hal:13: Pin 'ATCduinoui.hal_spinbutton13-s' does not exist
Shutting down and cleaning up LinuxCNC...
ATC has been disconnected
Note: Using POSIX non-realtime
pwmgen: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
stepgen: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
hal_parport: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
hypot: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
ddt: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
motmod: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
Note: Using POSIX non-realtime
trivkins: not loaded
<commandline>:0: exit value: 255
<commandline>:0: rmmod failed, returned -1
<commandline>:0: unloadrt failed
Note: Using POSIX non-realtime
LinuxCNC terminated with an error.  You can find more information in the log:
    /home/cnc/linuxcnc_debug.txt
and
    /home/cnc/linuxcnc_print.txt
as well as in the output of the shell command 'dmesg' and in the terminal

**Comment by mardini1974** [comment]
If I read the debug correctly I see you have a "GMOCCAPY GUI" Named "Freza".
there are two modifications on the ini file "freza.ini"
```
# ATCduino settings ------------------------------------------------------------
EMBED_TAB_NAME = ATC
EMBED_TAB_COMMAND =  gladevcp  -u ATCduinoui.py -x {XID} ./ATCduinoui.ui
EMBED_TAB_LOCATION = ntb_preview
#===============================================================================
```
and 

```
#########################################Masoun
#SUBROUTINE_PATH = macros
SUBROUTINE_PATH = nc_subroutines:python:../../nc_files/remap_lib/common_nc_subs:macros
LOG_LEVEL = 9
FEATURES = 30
ON_ABORT_COMMAND = O <on_abort> call
REMAP=M6   modalgroup=6  prolog=change_prolog   ngc=rack_change  epilog=change_epilog

[CHANGE_POSITION]
X = 10
Y = 100
Z = -50

[ATCPINS]
# This is the pin number which connected to motion.digital-out-xx
##outputs

PISTON = 0
HOME = 1
#Change this pin number to match machine's  spindle digital output number .
LOCK = 2
SAVEEPROM = 3

#inputs

ENABLE = 0
INPOSITION = 1

#Analog output
CMDSTATION = 0

[DWELL]
LOCK_TIME = 1.5
MYSTERY = 2
NEW_TOOL = 1.0
POST_UNLOCK = 0.5
PISTON_TIME_OUT = 2
TURNING_TIME_OUT = 25
[STATIONS]
S1 = 0
S2 = 8384
S3 = 16768
S4 = 25152
S5 = 33536
S6 = 41920
S7 = 50304
S8 = 58688

[HOMING]
OFFSET = 4000
HSPEED = 200
HOFFSETSPEED = 200
RSPEED = 200

[PID]
ATCP = 37
ATCI = 32
ATCD = 0.57

#################################################
```
the missing spinbutton13 and so on reading is coming from file "Atcduino_gui.hal"
```
net ATCduino.gui.hspeed ATCduino.hspeed ATCduinoui.hal_spinbutton13-s
net ATCduino.gui.hoffsetspeed ATCduino.hoffsetspeed ATCduinoui.hal_spinbutton14-s
net ATCduino.gui.rspeed ATCduino.rspeed ATCduinoui.hal_spinbutton15-s
```
which as per "ATCduinoui.py" getting it from ini file [HOMING]/[HSPEED, HOFFSETSPEED, RSPEED]

```
        self.spin.set_value(int(inifile.find("HOMING", "HSPEED") or 0))
        self.spin = self.builder.get_object("hal_spinbutton14")
        self.spin.set_value(int(inifile.find("HOMING", "HOFFSETSPEED") or 0))
        self.spin = self.builder.get_object("hal_spinbutton15")
        self.spin.set_value(int(inifile.find("HOMING", "RSPEED") or 0))
```
please check in your "Freza.ini"  that you have these items.

I think we try to pass firstly reading of the missing values and then we check the missing handlers

**Comment by Sekai1942** [comment]
I archived the whole directory.
I know that i did everything correctly.
[freza.zip](https://github.com/mardini1974/ATCduino/files/7626574/freza.zip)
